//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public int NomineeId { get; set; }
        public Nullable<long> AccId { get; set; }
        public string FullName { get; set; }
        public string Relationship { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string AdharNo { get; set; }
        public string Address { get; set; }
    
        public virtual Account_mst Account_mst { get; set; }
    }
}
