//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<long> FromAcId { get; set; }
        public Nullable<long> ToAcId { get; set; }
        public decimal Amount { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Account_mst Account_mst { get; set; }
        public virtual Account_mst Account_mst1 { get; set; }
    }
}
