//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Platform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Account_mst = new HashSet<Account_mst>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Gmail { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Pin { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> DOO { get; set; }
        public int Role { get; set; }
        public string AadharNo { get; set; }
        public string PAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_mst> Account_mst { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
